### ISSUE TITLE
Having trouble with images from today

### ISSUE THREAD

**Issue by bronwynagrios** [AstroDigital/libra#12]
On load, the date slider shows the last available date as today's date.
![screenshot 2015-03-19 20 06 43](https://cloud.githubusercontent.com/assets/4359871/6745386/8d7b3940-ce73-11e4-8341-089853d7ec9c.png)

As soon as I click to open the date filter to change the date, the most recent available date changes to yesterday.
![screenshot 2015-03-19 20 07 36](https://cloud.githubusercontent.com/assets/4359871/6745401/b0c3720a-ce73-11e4-825e-46de665139f0.png)

If I update the date filter to only show me images from yesterday and today then I get incorrect information. The map does not update and the results show that there is no data available but the error message here is not very helpful.
![screenshot 2015-03-19 20 09 38](https://cloud.githubusercontent.com/assets/4359871/6745431/fdaa35fe-ce73-11e4-9e90-05a3e7efd877.png)

**Comment by drewbo** [comment]
@bronwynagrios thanks for tagging. This is four separate errors:
1. The date ticking back a day is a [known issue](https://github.com/AstroDigital/libra#known-issues) that isn't especially urgent (although we should still fix at some point) because we never have "today's" data since we download the metadata `.csv` each night.
2. The error message not being helpful is similar in kind to another [known issue](https://github.com/AstroDigital/libra#known-issues) but is a different case. Basically we return the same error if you don't get any results from the api call so we need to either distinguish between "zooming too much" temporarily vs. spatially or return a more generic message
3. Map not updating after this error is super confusing, opened in #13 
4. Not having yesterday's data is a result of updating errors in [landsat-api](https://github.com/developmentseed/landsat-api). Not likely an issue with the repo code itself but something with the cron job that updates the data. @scisco any idea on this?
