### ISSUE TITLE
Example band selection pictures not appearing

### ISSUE THREAD

**Issue by drewbo** [AstroDigital/libra#8]
Getting a 403 error 
![screen shot 2015-03-05 at 6 48 12 pm](https://cloud.githubusercontent.com/assets/7108211/6517350/32d46a0e-c368-11e4-9fa0-d14efde057c8.png)

**Comment by jflasher** [comment]
I think this is the direction to fix the build issue with ng-src, I tried it but it's messing up the other images in the build. My regex-foo is failing. 

https://github.com/yeoman/grunt-usemin/issues/497#issuecomment-75400354

**Comment by stephanebachelier** [comment]
Feel free to come back to me if you need help on usemin part.

**Comment by jflasher** [comment]
Thanks @stephanebachelier I think I figured out what's happening, but not sure why. I've included the regex in patterns at https://github.com/AstroDigital/libra/commit/3909a16a8cba39e3b317bdd5e5fd44c3473e8cef but when I run this, no other patterns are getting matched (though ng-src is matched). So none of the other js, css or images are getting caught and renamed. It looks like I am overriding the default patterns instead of adding to them. Am I missing something obvious? Thanks!
